---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_URI: AgA/uYhlbtslF1cE5hs0MWepeX8E8Vby1xzCSRFoTXjMAJSDgYeX5gQjh/c0CbeE2eArET5FmH43RfCT5iNAbTONYy+mFtdmiVYd9DSs7I5TBmnjbSsMsebm0YhBpg/K+BXIMLZ6SKxPN0Zu18L0FaGcwkw58KbwxzNFcwo2rL0RWzmTZV0eFgw+FlqaDZ0YQkBP5907h9P/TknsH+0ib+ZDmMdwgumwocMGtnbXD8wXhLMv7mERePMLXT2GVUcNg1biB/fNYgOl/5FC+zqyeRfQ96Frw4PSdBsp6/PxCTDz+tvCskaGuWo2CfjpIY/E23fgZ/G+H9mO5NaK0NnJbc1elg69rSHFyv55g8fptpTEHaUrKVBAx1Rh8Os4pOyY1vnMGkw+4tICilJTr+9xUQaqw1zbhWpaWc4rUeQdXvc2HTvVBeyJxLsMAYT4L0sPxqq5Ulu1ucmUixo88al0Z6C3tnPdAVvC/Vhr4Kfma0RNf3aRqN3a5eXapwfnrCDpWd/dfw03rs+4UfQj3rQIynw8HvbO9cWjV0gIjsrRjLS1ODjmrN3DQGiHfRcKEh6ilqGAjtv05TbWYpXcCSU3D5A8Mf0VfjihqwKiplafvlICE38H14NwF/YZSq4ILlac+qSC2qOKMmmlmzf9E5KIGewQApzJzpjoqP7JOmTbGL/gm9wJXUyrgjMhpQXCcDAdNomf2pwczmKUyIhjl1giJhKmE0P0qkBN5D5YuIzfuf9+xnfQMh82XLjmH4JzCXLSdPvsoRxbYN+b6KOdv9G5T7Ez0AWHtg==
  template:
    metadata:
      name: backend-secrets
      namespace: default
