---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_URI: AgBqNhRevZD+YOOdIRZ/dN2/4khG7HZsn5+M+WzDCPlAKKQOHR4QN93TsQwjOXXW/ia3cqIG4amv+y6ppSgLdPqYQsofFwpxnDKWIA/0kOflb/E+FzTVLkOkRrsE7NMdCRjIic32Ccfi1n2LRi8FubKxZ+X6a46TcErDaQXJ4CcnyAhDd07ZOqSkC/likKp5GJSkznk+hyO8QKB+QaQE8fSJf6Pe6e3OmI12/wUX76tMZ/cx5fXkjKcS0eSCEd28CzAJqiuq2yp2DMxcvEYRMXvCArYQ7pJj9A2AWaQ+DPk8oiMCb9CixKBk4JmhjjxVi9neLb2rfbCkj0nF+raGPWuxjA5HJfXXSv70dSmxRF5/JdWnvSpH3OdYtv5E1B3KTS0XQN5MyTddg6QySm0pE8zH1amzV82rjDNo6S1bJAiMEfmDfMlNiGO3WCJLqwdTSPVfwZ7P8t3iACr7cJK/9HqcH3YiF1pMAONpC5XAmxFA9ztA0SENNGbY9mMUiXaC/U7FX7fYT2n9REsFMmA1+aWZXFyHF2CRtWUYnGhdoLdCvNp4bH3n0Lq/chiM6LF/CJwYHCPAd1Lqg/ktae7qu5V1tGsu9kIJr0X58ekOhKoNAmxwJbwUrKr9ihArv1jOjDjY6Hwl4MJSvRN4/uxk+swjFgOP92pkCKF9m0rd1EK/v+krQcdIjga7EcbCqZ5bR/v4X1ZA6Xp+Y8AHOVHk5MdTnSY5KKp71GpRUBTbr6TPEUIl2ZuS0uLfZwGq79iOGFgqCaBCrsRZDA158L+e0g3JUc1cRg==
  template:
    metadata:
      name: backend-secrets
      namespace: default
