---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgCPLoHPP8fVfFlVQwFaBkzPXJswVT03nw/VRX+3gv3QuvoylYfJs8UasbGGtIcJwj8E2WIZNsbJkoBOrjHfcl5dpzowAsklySBTaFZ30bHjMmMUBBHHevGkvwVIEQysUKZBkIcLGMxA2JIaTPzQus69gSFPZTHjfQ7eRZLSLsf0T0JT4Xu45ERY3oUnnFzqnATZ5TAiL8ufD6q9BRAVTP1VKKSgmeGT1gC+LkiRJCgW60S3eDnoyPBEihamBMi2R4/e4c+lTm3cC+pY/imtNzkIX+wT0HO6JnZi2Z5JmP0TjZimdQgsAp+2qG13VnUsVRm+K7R1CZCEvDd7rnoGn7Ljpy/BXVgbc6aP1W4Noa57vVLXRlJHDYDIwVkjgYGmBHjrBJk6QyARcuef7/OL8MIgdPAcKw6Z8hRglj6C+5HO+CwcPO4aetNKRjQVJaQz2iht03iynBTLKH/bLMgAZlGKCGwiQ11COVIC4p9roTeK0w3F6lohui2skPX38Rc/MNEZICVpO/JRcO75blT0ml6GIDKRgJQFmGkO+zfGIs6/mWFHrHY9Xe+2xAzKNnriiDvQlMcZbNGQhz+1cTJHtYA5VFBJV/ImalsxlWFq6fehvlySi9SMqdrfEpOgkVNv/S7emsYhl4Xt7sXXE/eX0FXYcJv62q9klSWHfUuN4sAJ7u4DskvBgp9EhtmVDyktScSw1A2IJZwNJzUp
    MONGO_INITDB_ROOT_USERNAME: AgCILfufUT+mq8KahSqnENBRdimF+9+W8Rh2M8X/tZnVNUmb3blSOQfkChcxTR9XhC5VTOLixFOxUC104Tjwmp2wd5GGW/RuhhNipEM7Gv0tJ7xZtS1a10eOdAJeMvU2P7NzgPc+zOoe8CmUIciJScDhOxd3WmbQR9wlws0eWghQwTnrHG7sBZg1tszlAsmt5+U6N0yQeAP1ruoCrPfqsPtkRxlq4LkP+Og+nNh8cH2dI11zw2ImUHrgXZZRt4MSFisaSEgp/A8kwbpqJMQ+76k2OI05pnWIQc30p4R1OX2GGuNJVLpYjqrXJCNeNT22Qc8AI6AcLlkPYWLrXaNyCt603W15HFrBrZLnXxd36g/oaARG+WKDUFDXnY29TtjUott57s0B6ASfsPK6gviGONtchltCYmDhv0YfeZDgZMSlDzzeFoJW8q6r9T7WsWuaHhR/nBAZAZ2v8IeFuid/ZXtVzmKeWHPoGHUbsodT1Rd0mnCFex02IPoXnv9IPPR/a9/53XbT7mSbQLfvsBbZk6L4Pl0tK364f1o1iTVgmmklXrNnU71j4euFwWGKNSz+WUTRIq+I6GojEAL3zXY0Ty3WBVXIqq70YAyx+ttIcRP8jfS8zJqF6mIIFGiZtrVraVwXIicyE83YnYx6GX7DkRrFlhrRS5kS/nynjZOh9JgMJmH1gVN09+hptPYdnu+JecXQiFVA/Q==
  template:
    metadata:
      name: mongo-secrets
      namespace: default
