---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgBVU+U6cqcdZZc52SKW6QC4y8GzeN5LajR7etYAPxaeamC/QYFI0f4T9EudtpOshMommK1U0VcktXIOyqSMx6AnSmf/RAT5djYjhgeX86Ic5bihaX7mqSuwyjnei9lHwXITJV8q4o4WNz3ZUMGZZ5809g0bgoO0GJVkRiVd8NWMCfppgLExrefa440yOdNH6/Mz1/wBQx9frdwq61AO1U7qQmyHit1a1eb7W3wRTO9anpeirlcjQ185L/R2QEkgbSZ5B/1Lyq8soyJUHQpz53WSumup6Yon3zv0IbM+qvxiwFHZz1z9uEE1SlzNiGoeY7UgVJlEjPGBfsQRuKlAi+aql+Izb7PzBw/R11lpD6fh2PWFoAlPb75fGY6dT7cbKxp/AzBBKjnGDBuyIbrf+VEikmQfr2cHSVMTAoIM6pP55PoVgnRi5dG2tSsLGnwe5CfPp1ZG0IbSOHO8oEPrlA3YBVtFzyyKS7+u2p9gcByozTftWtuo3WFtu1Yfovuavdhd2ATis2lYWzLTKBrzRn7iCUdjdtuLpwWVkNkObGtbiN3HgIUoIYOliQdFQPzj2TsVfu2vtxx0WnWjsQ0zJ1KBJ9nE/TALeomANxHGgwapYsDwhm4kvPJDPr55/66WtHQXexfferRc/0JBRawtDOGqEortwLXCVoPeLBo3uyBOlp5KmYdXVDrCHZQjVa/ubYSk3NkSrkG5wMb8
    MONGO_INITDB_ROOT_USERNAME: AgAOXEdFIcll+hXg40WREO5X3EOne6aJ9b9FZTN1WirsIXs5M4C2009M0vTR/yn5hABcwvPrSyhTBdJB/YtJGKBsrT7hFYSGCUqZqupJUPi1iG4skMH44nhYW7+6MlGy1uvrZ5vwDWKx+A0j7cOkwh34UtTq6D9TyxTOrt1RH9E50OfMs9c1sV3uJ0+lqGUSzuMYonxVDIoOPLGwEqd9AIyJ1rKQD3kg1Bdqlgfmt19YnEKh83WNZU771LGliwV/fw0whZ7t8G3MYrwWF92SCCrl1tYxzEJeLfM0apkiXL+UuRYLK0cWaPVFnGn2OCCXYWyy/vjUg3YDC2In9UAHlUGY6HSC6rdna6y9kf6Qd/vJhFeahUWyiZrd8emJW8qSzVdUyfBMhOOGLxmDgn3IunSNC8h4EHL/77gi5hGELb+ZSObInDGLGd0OlmpCgAAxh78fBY4Df/vIgMXMJkcVfwIpHV5TxopV/08lpZB15QMzCDU1hAjrSHKkiSLX5BfGFTHfVdhCdj2GZmHk9U1HHVyVspJmA7nyWdYf5StBpWshlhpTqtoymh1AtzZ88QvGUcEXEYKmWzXTpBoTGgEyctqECWPvqo8/ABLtDCEkSNXP0Qf9QavaT9BMWRaKsSneF9mGvQkfTcbhywblZSqg2ijd6Nlf23jQ5h5SJc7GWrMq/3HTMI1PwWyFRRc3Z8eUdGvigTF9pw==
  template:
    metadata:
      name: mongo-secrets
      namespace: default
